/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package local_gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import org.edisoncor.gui.util.Avatar;

/**
 *
 * @author thato
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarMenu();
    }

    public void llenarMenu()
    {
    List<Avatar> avatars=new ArrayList<Avatar>();
    avatars.add(new Avatar("Cartola",loadImage("/img/Cartola.png")));
    avatars.add(new Avatar("Cliente",loadImage("/img/Cliente.png")));
    avatars.add(new Avatar("Traspaso",loadImage("/img/Traspaso.png")));
    avatars.add(new Avatar("Deposito",loadImage("/img/Deposito.png")));
    avatars.add(new Avatar("Giro",loadImage("/img/Giro.png")));
    avatars.add(new Avatar("Salir",loadImage("/img/Salir.png")));
    menu.setAvatars(avatars);
    }
    
    public static Image loadImage(String fileName)
    {
        try {
            return ImageIO.read(Menu.class.getResource(fileName));
        } catch (Exception e)  {
        return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        menu = new org.edisoncor.gui.panel.PanelAvatarChooser();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAction1.setText("Ingresar");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });
        menu.add(buttonAction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        panelNice1.add(menu, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        if(menu.getSelectedtitulo().equals("Cartola"))
        {
            Cartola ca = new Cartola();
            ca.setVisible(true);
            this.setVisible(false);
            
        }
        if(menu.getSelectedtitulo().equals("Cliente"))
        {
            Cliente cli = new Cliente();
            cli.setVisible(true);
            this.setVisible(false);
        }
        if(menu.getSelectedtitulo().equals("Traspaso"))
        {
            Traspaso tr = new Traspaso();
            tr.setVisible(true);
            this.setVisible(false);
        }
        if(menu.getSelectedtitulo().equals("Giro"))
        {
            Giro gr = new Giro();
            gr.setVisible(true);
            this.setVisible(false);
        }
        if(menu.getSelectedtitulo().equals("Deposito"))
        {
            Deposito dp = new Deposito();
            dp.setVisible(true);
            this.setVisible(false);
        }
        if(menu.getSelectedtitulo().equals("Salir"))
        {
            System.exit(0);
        }
    }//GEN-LAST:event_buttonAction1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.panel.PanelAvatarChooser menu;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
private void close()    {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
